name: wedding_site
description: "Website for our wedding"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  freezed_annotation: ^2.4.1
  flutter_sticky_header: ^0.6.5
  google_fonts: ^6.1.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

